name: Generate docs

on:
  push:

jobs:
  docs:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/prepare
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: docs-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Generate docs
      run: cargo doc --all --no-deps
    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc
        force_orphan: true